# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 13:05
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=512, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=512, verbose_name='Имя')),
                ('phone', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(regex='\\+7\\-\\([0-9]{3}\\)\\-[0-9]{3}\\-[0-9]{4}')], verbose_name='Телефон')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
